### ISSUE TITLE
get_encoder_counts and get_battery_voltage do not work

### ISSUE THREAD

**Issue by RobinAmsters** [RobinAmsters/GT_mobile_robotics#2]
The message files on github might be out of sync wit the message files on the Turtlebot. The correct files are on the local repo.

**TODO**:

- [x] Test installation on a clean machine
- [x] Merge develop into master
- [x] Push to github
- [x] Upload to Toledo
